// Generated by CoffeeScript 1.6.3
(function() {
  var async, bkp, bulk, copy, count, createIndex, deleteIndex, extend, fs, getIndex, map, query, req, setConfig, _config, _log, _r_oper;

  async = require("async");

  fs = require("fs");

  req = require("request");

  extend = require("util")._extend;

  _config = null;

  setConfig = function(config) {
    return _config = config;
  };

  bulk = function(opts, docs, done) {
    var action, doc, index, obj, oper_opts, res, type, _doc, _i, _len;
    if (!Array.isArray(docs)) {
      done("docs not array");
    }
    if (!docs.length) {
      done(null, []);
      return;
    }
    res = "";
    for (_i = 0, _len = docs.length; _i < _len; _i++) {
      doc = docs[_i];
      obj = {};
      index = doc._index;
      if (index == null) {
        index = opts.index;
      }
      if (opts.index_prefix) {
        index = opts.index_prefix + "." + index;
      }
      action = doc._action ? doc._action : (opts.action ? opts.action : "index");
      type = doc._type ? doc._type : opts.type;
      obj[action] = {
        _index: index,
        _type: type,
        _id: doc._id
      };
      res += JSON.stringify(obj);
      res += "\r\n";
      _doc = extend({}, doc);
      delete _doc._id;
      delete _doc._index;
      delete _doc._type;
      delete _doc._action;
      if (action !== "delete") {
        res += JSON.stringify(_doc);
        res += "\r\n";
      }
    }
    oper_opts = extend(extend({}, opts), {
      uri: opts.uri,
      index: null,
      type: null,
      oper: "_bulk",
      method: "post",
      body: res
    });
    return _r_oper(oper_opts, done);
  };

  map = function(uri, fromIndex, toIndex, docsCount, map, done) {
    if (docsCount == null) {
      docsCount = 10000;
    }
    return req.get({
      uri: "" + uri + "/" + fromIndex + "/_search",
      qs: {
        size: docsCount
      }
    }, function(err, res) {
      var j;
      if (!err) {
        j = JSON.parse(res.body);
        j = j.hits.hits.map(function(m) {
          return map(m);
        });
        return bulk(uri, toIndex, j, done);
      } else {
        return done(err);
      }
    });
  };

  copy = function(uri, fromIndex, toIndex, done) {
    return map(uri, fromIndex, toIndex, null, (function(m) {
      return m;
    }), done);
  };

  getIndex = function(opts, done) {
    return _r_oper({
      uri: opts.uri,
      index: opts.index,
      method: "get"
    }, done);
  };

  deleteIndex = function(opts, done) {
    return _r_oper(extend({
      method: "delete"
    }, opts), done);
  };

  createIndex = function(opts, done) {
    var settings;
    settings = opts.settings;
    if (!settings) {
      settings = JSON.parse(fs.readFileSync(opts.settingsPath, "utf-8"));
    }
    return _r_oper(extend({
      method: "post",
      body: settings
    }, opts), done);
  };

  bkp = function(opts, done) {
    return async.waterfall([
      function(ck) {
        return deleteIndex(opts, ck);
      }, function(ck) {
        return createIndex(opts, ck);
      }, function(ck) {
        return copy(opts, ck);
      }
    ], done);
  };

  query = function(opts, body, done) {
    var params;
    params = extend({
      body: body
    }, opts);
    if (!opts.id) {
      params.oper = "_search";
    }
    return _r_oper(params, done);
  };

  count = function(opts, done) {
    var params;
    params = extend({
      oper: "_count"
    }, opts);
    if (params.body && params.body.query) {
      params.body = params.body.query;
    }
    return _r_oper(params, function(err, data) {
      if (!err) {
        data = {
          count: data.count
        };
      }
      return done(err, data);
    });
  };

  _log = function() {
    var arg, json_arg, str_arg, _i, _len, _ref;
    console.log("--->>>");
    _ref = Array.prototype.slice.call(arguments, 0);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      if (arg) {
        json_arg = typeof arg === "string" ? JSON.parse(arg) : arg;
        str_arg = JSON.stringify(json_arg, null, 2);
        if (str_arg.length > 500) {
          str_arg = str_arg.substring(str_arg, 500) + "...";
        }
      } else {
        str_arg = arg;
      }
      console.log(str_arg);
    }
    return console.log("<<<---");
  };

  _r_oper = function(params, done) {
    var index, opts;
    opts = {
      uri: params.uri
    };
    if (opts.uri == null) {
      opts.uri = _config.uri;
    }
    index = params.index;
    if (index && params.index_prefix) {
      index = params.index_prefix + "." + index;
    }
    if (index) {
      opts.uri += '/' + index;
    }
    if (params.type) {
      opts.uri += '/' + params.type;
    }
    if (params.oper) {
      opts.uri += '/' + params.oper;
    }
    if (params.id) {
      opts.uri += '/' + params.id;
    }
    /* body*/

    if (typeof params.body === "object") {
      opts.json = params.body;
    } else {
      opts.body = params.body;
    }
    /* method*/

    if (params.method) {
      opts.method = params.method;
    }
    return req(opts, function(err, res) {
      var e;
      if (params.debug) {
        _log(err, opts, res.body);
      }
      if (!err && res && res.body) {
        res = res.body;
        try {
          if (typeof res === "string") {
            res = JSON.parse(res);
          }
        } catch (_error) {
          e = _error;
          done(res);
          return;
        }
        if (!res.error) {
          return done(err, res);
        } else {
          return done(res.error);
        }
      } else {
        return done(err);
      }
    });
  };

  exports.setConfig = setConfig;

  exports.createIndex = createIndex;

  exports.deleteIndex = deleteIndex;

  exports.getIndex = getIndex;

  exports.copy = copy;

  exports.bulk = bulk;

  exports.map = map;

  exports.bkp = bkp;

  exports.query = query;

  exports.count = count;

}).call(this);
